#!/bin/bash

POW_PID=`curl -H host:pow localhost/status.json | sed 's/{"pid"://' | sed 's/,.*//'`

for i in `top -l 1 | grep node | awk '{ print $1 }'`; do
#  if [ $i != $POW_PID ]; then
    kill -HUP $i
#  fi
done
